### ISSUE TITLE
cross browser sticky footer

### ISSUE THREAD

**Issue by simboonlong** [Open-Attestation/verify.gov.sg#50]
- will need to refactor top navbar outside
- then main content can flex grow properly

**Comment by Nebulis** [comment]
IIRC the problem was that the navbar was different accross the pages

**Comment by simboonlong** [comment]
right.. ok let me figure sth out

**Comment by simboonlong** [comment]
resolved in https://github.com/Open-Attestation/verify.gov.sg/pull/52
