### ISSUE TITLE
Verifying against a Quorum/ethereum private blockchain

### ISSUE THREAD

**Issue by supportreq** [Open-Attestation/verify.gov.sg#73]
Is there way to verify the generated opencert document against a private ethereum / quorum blockchain?

If yes what is to be modified?

**Comment by Nebulis** [comment]
Hi,

A better place to discuss about this would be on OpenAttestation organisation. This portal will not support private blockchain. 

As for quorum we have no plans to do it. So i fyou feel that we should, feel free to argue and suggest how to implement it. That does not mean we will work on it though.
